app:
  port: 8080
  host: 127.0.0.1
  env: dev
  logfiles: /logs

database:
  driver: mysql
  migrate: true
  # use dsn
  dsn: fortest:test@tcp(127.0.0.1:3306)/fortest?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms

redis:
  enable: true
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
